#!/bin/bash
#
# Script en backgroud qui surveille l'ouverture de certains fichiers
#
# Fichiers de configuration 
#
#       watch_dog.txt  : contient la liste des fichiers a surveiller
#       watch_dog.conf : contient les parametres de configuration du script 
#
#
# timeout=2 secondes
# 
# Vidage du fichier : /tmp/watch_dog.log
. watch_dog.conf 
>"$log"  
while true
do
    for fic in $(cat watch_dog.txt)
    do
        if lsof "$fic" >/dev/null 2>&1
        then
            echo "$(date) : fichier $fic ouvert" >> "$log"
        fi
    done
    sleep $timeout
done &    

